import type {
  Activity,
  DataIntakeRecord,
  Project,
  Risk,
} from "@/types";

// Static mock data for the frontend prototype. Shapes match the
// contracts future backend APIs are expected to fulfill.

export const projects: Project[] = [
  {
    id: "prj-001",
    code: "NH-44-B2",
    name: "NH-44 Bridge Widening — Package B2",
    location: "Nagpur, Maharashtra",
    sector: "Highways",
    status: "on-track",
    progress: 62,
    startDate: "2025-02-10",
    endDate: "2026-11-30",
    budgetUtilized: 58,
    contractor: "L&T Infra JV",
  },
  {
    id: "prj-002",
    code: "MRT-3-C7",
    name: "Metro Corridor 3 — Elevated Section C7",
    location: "Pune, Maharashtra",
    sector: "Urban Transit",
    status: "at-risk",
    progress: 41,
    startDate: "2024-08-01",
    endDate: "2027-03-31",
    budgetUtilized: 47,
    contractor: "Afcons Infrastructure",
  },
  {
    id: "prj-003",
    code: "IRR-KRN-9",
    name: "Krishna River Lift Irrigation Scheme — Phase 9",
    location: "Raichur, Karnataka",
    sector: "Irrigation",
    status: "delayed",
    progress: 29,
    startDate: "2024-04-15",
    endDate: "2026-06-30",
    budgetUtilized: 39,
    contractor: "NCC Limited",
  },
  {
    id: "prj-004",
    code: "PWR-GRD-14",
    name: "765kV Transmission Corridor — Segment 14",
    location: "Bhopal, Madhya Pradesh",
    sector: "Power",
    status: "on-track",
    progress: 74,
    startDate: "2024-11-01",
    endDate: "2026-02-28",
    budgetUtilized: 69,
    contractor: "KEC International",
  },
  {
    id: "prj-005",
    code: "SMRT-WTR-2",
    name: "Smart Water Distribution Network — Zone 2",
    location: "Coimbatore, Tamil Nadu",
    sector: "Water & Sanitation",
    status: "completed",
    progress: 100,
    startDate: "2023-06-01",
    endDate: "2025-05-15",
    budgetUtilized: 96,
    contractor: "VA Tech Wabag",
  },
];

export const activities: Activity[] = [
  {
    id: "act-001",
    projectId: "prj-001",
    code: "B2-EW-04",
    name: "Pier foundation excavation — P4 to P7",
    wbsPath: "2.1.4",
    owner: "R. Deshmukh",
    status: "in-progress",
    progress: 68,
    plannedStart: "2025-12-01",
    plannedEnd: "2026-01-20",
    actualStart: "2025-12-04",
    linkedRecords: 6,
  },
  {
    id: "act-002",
    projectId: "prj-001",
    code: "B2-SS-11",
    name: "Steel superstructure launching — Span 3",
    wbsPath: "3.2.1",
    owner: "A. Kulkarni",
    status: "not-started",
    progress: 0,
    plannedStart: "2026-02-05",
    plannedEnd: "2026-04-15",
    linkedRecords: 0,
  },
  {
    id: "act-003",
    projectId: "prj-001",
    code: "B2-QA-02",
    name: "Deck concrete pour quality audit",
    wbsPath: "3.1.6",
    owner: "S. Nair",
    status: "completed",
    progress: 100,
    plannedStart: "2025-10-10",
    plannedEnd: "2025-10-28",
    actualStart: "2025-10-10",
    actualEnd: "2025-10-30",
    linkedRecords: 9,
  },
  {
    id: "act-004",
    projectId: "prj-002",
    code: "C7-TBM-08",
    name: "TBM drive — Chainage 4+200 to 5+000",
    wbsPath: "1.4.2",
    owner: "V. Rao",
    status: "delayed",
    progress: 33,
    plannedStart: "2025-09-01",
    plannedEnd: "2025-12-15",
    actualStart: "2025-09-08",
    linkedRecords: 14,
  },
  {
    id: "act-005",
    projectId: "prj-002",
    code: "C7-UTL-03",
    name: "Utility diversion — water mains, Sector 12",
    wbsPath: "1.2.5",
    owner: "M. Iyer",
    status: "blocked",
    progress: 18,
    plannedStart: "2025-11-01",
    plannedEnd: "2025-12-20",
    actualStart: "2025-11-05",
    linkedRecords: 4,
  },
  {
    id: "act-006",
    projectId: "prj-002",
    code: "C7-STN-01",
    name: "Station box shoring — Concourse level",
    wbsPath: "2.3.1",
    owner: "K. Bhatt",
    status: "in-progress",
    progress: 55,
    plannedStart: "2025-10-15",
    plannedEnd: "2026-01-30",
    actualStart: "2025-10-18",
    linkedRecords: 8,
  },
  {
    id: "act-007",
    projectId: "prj-003",
    code: "K9-CNL-06",
    name: "Main canal lining — RD 12.5 to RD 18.0",
    wbsPath: "4.1.3",
    owner: "P. Hegde",
    status: "delayed",
    progress: 21,
    plannedStart: "2025-07-01",
    plannedEnd: "2025-11-30",
    actualStart: "2025-07-20",
    linkedRecords: 5,
  },
  {
    id: "act-008",
    projectId: "prj-003",
    code: "K9-PMP-02",
    name: "Pump house electromechanical installation",
    wbsPath: "5.2.2",
    owner: "T. Gowda",
    status: "not-started",
    progress: 0,
    plannedStart: "2026-01-10",
    plannedEnd: "2026-03-25",
    linkedRecords: 1,
  },
  {
    id: "act-009",
    projectId: "prj-004",
    code: "S14-TWR-19",
    name: "Tower erection — Section 19 to 26",
    wbsPath: "2.2.7",
    owner: "D. Chauhan",
    status: "in-progress",
    progress: 81,
    plannedStart: "2025-08-01",
    plannedEnd: "2025-12-31",
    actualStart: "2025-08-03",
    linkedRecords: 11,
  },
  {
    id: "act-010",
    projectId: "prj-004",
    code: "S14-STR-05",
    name: "Conductor stringing — Section 19 to 26",
    wbsPath: "2.4.1",
    owner: "N. Verma",
    status: "not-started",
    progress: 0,
    plannedStart: "2026-01-05",
    plannedEnd: "2026-02-20",
    linkedRecords: 0,
  },
  {
    id: "act-011",
    projectId: "prj-005",
    code: "Z2-DMA-04",
    name: "District metering area commissioning",
    wbsPath: "6.1.1",
    owner: "L. Pillai",
    status: "completed",
    progress: 100,
    plannedStart: "2025-03-01",
    plannedEnd: "2025-04-30",
    actualStart: "2025-03-01",
    actualEnd: "2025-04-22",
    linkedRecords: 7,
  },
  {
    id: "act-012",
    projectId: "prj-005",
    code: "Z2-SCD-01",
    name: "SCADA integration and handover",
    wbsPath: "6.3.2",
    owner: "L. Pillai",
    status: "completed",
    progress: 100,
    plannedStart: "2025-04-15",
    plannedEnd: "2025-05-10",
    actualStart: "2025-04-15",
    actualEnd: "2025-05-08",
    linkedRecords: 3,
  },
];

export const risks: Risk[] = [
  {
    id: "risk-001",
    projectId: "prj-001",
    code: "R-B2-07",
    title: "Monsoon-driven excavation delay at pier foundations",
    category: "Environmental",
    severity: "medium",
    likelihood: "likely",
    status: "monitoring",
    owner: "R. Deshmukh",
    linkedActivityId: "act-001",
    identifiedOn: "2025-11-02",
    dueDate: "2026-01-15",
  },
  {
    id: "risk-002",
    projectId: "prj-001",
    code: "R-B2-11",
    title: "Steel supplier lead-time slippage for Span 3",
    category: "Supply Chain",
    severity: "high",
    likelihood: "possible",
    status: "open",
    owner: "A. Kulkarni",
    linkedActivityId: "act-002",
    identifiedOn: "2025-12-01",
    dueDate: "2026-01-30",
  },
  {
    id: "risk-003",
    projectId: "prj-002",
    code: "R-C7-02",
    title: "TBM cutterhead wear beyond design tolerance",
    category: "Technical",
    severity: "critical",
    likelihood: "likely",
    status: "mitigating",
    owner: "V. Rao",
    linkedActivityId: "act-004",
    identifiedOn: "2025-10-20",
    dueDate: "2025-12-28",
  },
  {
    id: "risk-004",
    projectId: "prj-002",
    code: "R-C7-05",
    title: "Utility diversion clearance pending from municipal body",
    category: "Regulatory",
    severity: "high",
    likelihood: "almost-certain",
    status: "open",
    owner: "M. Iyer",
    linkedActivityId: "act-005",
    identifiedOn: "2025-11-10",
    dueDate: "2025-12-31",
  },
  {
    id: "risk-005",
    projectId: "prj-002",
    code: "R-C7-09",
    title: "Groundwater ingress at station box excavation",
    category: "Geotechnical",
    severity: "medium",
    likelihood: "possible",
    status: "monitoring",
    owner: "K. Bhatt",
    linkedActivityId: "act-006",
    identifiedOn: "2025-11-22",
  },
  {
    id: "risk-006",
    projectId: "prj-003",
    code: "R-K9-01",
    title: "Land acquisition dispute along canal RD 15.0",
    category: "Land & R&R",
    severity: "critical",
    likelihood: "almost-certain",
    status: "open",
    owner: "P. Hegde",
    linkedActivityId: "act-007",
    identifiedOn: "2025-08-05",
    dueDate: "2025-12-20",
  },
  {
    id: "risk-007",
    projectId: "prj-003",
    code: "R-K9-04",
    title: "Cement price escalation beyond contingency provision",
    category: "Financial",
    severity: "medium",
    likelihood: "likely",
    status: "monitoring",
    owner: "T. Gowda",
    identifiedOn: "2025-09-18",
  },
  {
    id: "risk-008",
    projectId: "prj-004",
    code: "R-S14-03",
    title: "Forest clearance renewal for tower corridor Section 22",
    category: "Regulatory",
    severity: "high",
    likelihood: "possible",
    status: "mitigating",
    owner: "D. Chauhan",
    linkedActivityId: "act-009",
    identifiedOn: "2025-09-30",
    dueDate: "2026-01-10",
  },
  {
    id: "risk-009",
    projectId: "prj-004",
    code: "R-S14-06",
    title: "Conductor stringing crew shortage during peak season",
    category: "Resourcing",
    severity: "low",
    likelihood: "possible",
    status: "open",
    owner: "N. Verma",
    linkedActivityId: "act-010",
    identifiedOn: "2025-12-05",
  },
  {
    id: "risk-010",
    projectId: "prj-005",
    code: "R-Z2-02",
    title: "Legacy SCADA compatibility gap at handover",
    category: "Technical",
    severity: "low",
    likelihood: "unlikely",
    status: "closed",
    owner: "L. Pillai",
    linkedActivityId: "act-012",
    identifiedOn: "2025-04-01",
    dueDate: "2025-05-01",
  },
];

export const intakeRecords: DataIntakeRecord[] = [
  {
    id: "intk-001",
    projectId: "prj-001",
    source: "site-report",
    fileName: "B2_DPR_2025-12-15.pdf",
    submittedBy: "R. Deshmukh",
    submittedOn: "2025-12-15",
    status: "linked",
    linkedActivityId: "act-001",
    confidence: 94,
    sizeKb: 1820,
  },
  {
    id: "intk-002",
    projectId: "prj-001",
    source: "drone-survey",
    fileName: "B2_Pier_Survey_Flight12.zip",
    submittedBy: "GeoScan Contractor",
    submittedOn: "2025-12-14",
    status: "pending-review",
    confidence: 71,
    sizeKb: 48200,
  },
  {
    id: "intk-003",
    projectId: "prj-001",
    source: "manual-entry",
    fileName: "Deck_Pour_QA_Checklist.xlsx",
    submittedBy: "S. Nair",
    submittedOn: "2025-10-29",
    status: "processed",
    linkedActivityId: "act-003",
    confidence: 100,
    sizeKb: 340,
  },
  {
    id: "intk-004",
    projectId: "prj-002",
    source: "sensor-feed",
    fileName: "TBM08_Telemetry_Batch_1144.json",
    submittedBy: "Automated Sensor Gateway",
    submittedOn: "2025-12-16",
    status: "flagged",
    linkedActivityId: "act-004",
    confidence: 58,
    sizeKb: 2210,
  },
  {
    id: "intk-005",
    projectId: "prj-002",
    source: "email",
    fileName: "Utility_Diversion_ClearanceUpdate.msg",
    submittedBy: "M. Iyer",
    submittedOn: "2025-12-11",
    status: "pending-review",
    confidence: 63,
    sizeKb: 210,
  },
  {
    id: "intk-006",
    projectId: "prj-002",
    source: "site-report",
    fileName: "C7_StationBox_Shoring_WeeklyReport.pdf",
    submittedBy: "K. Bhatt",
    submittedOn: "2025-12-10",
    status: "linked",
    linkedActivityId: "act-006",
    confidence: 89,
    sizeKb: 1120,
  },
  {
    id: "intk-007",
    projectId: "prj-003",
    source: "spreadsheet",
    fileName: "K9_Canal_Lining_Progress_Nov.xlsx",
    submittedBy: "P. Hegde",
    submittedOn: "2025-11-30",
    status: "linked",
    linkedActivityId: "act-007",
    confidence: 82,
    sizeKb: 560,
  },
  {
    id: "intk-008",
    projectId: "prj-003",
    source: "drone-survey",
    fileName: "K9_PumpHouse_SiteScan_Oct.zip",
    submittedBy: "AeroMap Surveys",
    submittedOn: "2025-10-22",
    status: "flagged",
    confidence: 41,
    sizeKb: 61300,
  },
  {
    id: "intk-009",
    projectId: "prj-004",
    source: "site-report",
    fileName: "S14_Tower_Erection_DPR_2025-12-12.pdf",
    submittedBy: "D. Chauhan",
    submittedOn: "2025-12-12",
    status: "linked",
    linkedActivityId: "act-009",
    confidence: 91,
    sizeKb: 1450,
  },
  {
    id: "intk-010",
    projectId: "prj-004",
    source: "manual-entry",
    fileName: "Forest_Clearance_Renewal_Note.docx",
    submittedBy: "D. Chauhan",
    submittedOn: "2025-12-08",
    status: "pending-review",
    confidence: 67,
    sizeKb: 180,
  },
  {
    id: "intk-011",
    projectId: "prj-005",
    source: "sensor-feed",
    fileName: "Z2_SCADA_Handover_Logs.json",
    submittedBy: "Automated Sensor Gateway",
    submittedOn: "2025-05-07",
    status: "processed",
    linkedActivityId: "act-012",
    confidence: 100,
    sizeKb: 3040,
  },
  {
    id: "intk-012",
    projectId: "prj-005",
    source: "spreadsheet",
    fileName: "Z2_DMA_Commissioning_Signoff.xlsx",
    submittedBy: "L. Pillai",
    submittedOn: "2025-04-23",
    status: "processed",
    linkedActivityId: "act-011",
    confidence: 98,
    sizeKb: 290,
  },
];
